# Exclude a variety of commonly ignored directories.
src = ["scene_synthesis"]
line-length = 120

[lint]
select = [
        "F", # pyflakes
        "C","E","R", "W",  # pylint (including pycodestyle)
        "C90", "I", "N","D", "UP",
        "YTT", "ASYNC", "ASYNC1", "BLE", "B", "A", "COM", # flake8 plugins
        "C4", "DTZ","T10","EM", "FA", "ISC", "ICN", # flake8 plugins
        "LOG", "G", "INP", "PIE", "T20", "PYI", "PT", "RSE", # flake8 plugins
        "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "ARG", "TD", # flake8 plugins
        "C901" # others
        ]

ignore = [
    "C901", # do we want to measure code complexity -> TBD
    "COM812", # conflict with ruff formatter
    "ISC001", # conflict with ruff formatter
    # D
    "D401", # first line should be in imperative mood -> TBD
    # Others
    "T20", # will be fixed when logging is implemented
    "SLF001", # should be fixed with issue: #225
]

[lint.flake8-import-conventions]
banned-from  = ["numba", "numpy", "scipy.linalg"]
[lint.flake8-import-conventions.aliases]
acoular = "ac"
numba = "nb"
numpy = "np"
"scipy.linalg" = "spla"
"matplotlib.pyplot" = "plt"

[lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 100

[lint.pydocstyle]
convention = "numpy"  # Accepts: "google", "numpy", or "pep257".

[format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 120
